### ISSUE TITLE
Displaying the strength of our password

### ISSUE THREAD

**Issue by ashwin3005** [ashwin3005/password-generator#10]
The current strength of our project must be displayed. (Example: weak, strong, very strong)

**Comment by AtriSukul1508** [comment]
I would like to work on this issue

**Comment by ashwin3005** [comment]
The strength of our password is at fair in minimum length(8) and strong in maximum length(32).
Other terms are not used..
@AtriSukul1508 could you fix it?

**Comment by hrithiksawhney** [comment]
Hi @ashwin3005 ,
Can I work on it?

**Comment by PavvanPradeep** [comment]
@ashwin3005 can i work on this issue

**Comment by ashwin3005** [comment]
@hrithiksawhney okay go ahead.

**Comment by ashwin3005** [comment]
> @ashwin3005 can i work on this issue

Can you take some other issue?

**Comment by hrithiksawhney** [comment]
Hi @ashwin3005 ,
Is it fine if we have the minimum password length as 1?

**Comment by hrithiksawhney** [comment]
Hi @ashwin3005,
Can you please reply to the above query?
