### ISSUE TITLE
Adding a normal header and footer

### ISSUE THREAD

**Issue by prakrit55** [ashwin3005/password-generator#33]
Will be putting a header and footer in the page. If this is agreed please assign this to me.

**Comment by ashwin3005** [comment]
okay, 
Go ahead..

But don't modify the  current UI much..

**Comment by prakrit55** [comment]
Okay @ashwin3005  can you put hactoberfest tag here?

**Comment by ashwin3005** [comment]
Sure..

**Comment by PavvanPradeep** [comment]
can i work on this

**Comment by ashwin3005** [comment]
Go ahead @PavvanPradeep
