### ISSUE TITLE
Lowercase checkbox 

### ISSUE THREAD

**Issue by ashwin3005** [ashwin3005/password-generator#38]
The lowercase checkbox must be checked by default.

**Comment by Ravina-Deogadkar** [comment]
can i take this issue?

**Comment by M-Rahul1** [comment]
I would like to contribute.
![Screenshot (15)](https://user-images.githubusercontent.com/68385075/194714400-6a9dcf48-1692-446d-9590-d1bc1eabc743.png)

**Comment by M-Rahul1** [comment]
@Ravina-Deogadkar if you are not doing can I take it. @ashwin3005

**Comment by ashwin3005** [comment]
okay.. take it
@M-Rahul1

**Comment by Ravina-Deogadkar** [comment]
I already started working on it

**Comment by ashwin3005** [comment]
Okay.
no problem.
Make a pull request while you are done..

**Comment by Ravina-Deogadkar** [comment]
Created pull request

https://github.com/ashwin3005/password-generator/pull/47

**Comment by ashwin3005** [comment]
So that now it is made default, 
but the lowercase is not excluded if we uncheck it..

**Comment by Ravina-Deogadkar** [comment]
Fixed it https://github.com/ashwin3005/password-generator/pull/49

**Comment by M-Rahul1** [comment]
Is it completed? @ashwin3005

**Comment by ashwin3005** [comment]
yeah
