### ISSUE TITLE
Create dark theme

### ISSUE THREAD

**Issue by ashwin3005** [ashwin3005/password-generator#4]
Implement dark theme by creating a toggle button.

**Comment by thisurathenuka** [comment]
Hi @ashwin3005 , Can I work on this, please?

**Comment by ashwin3005** [comment]
> Hi @ashwin3005 , Can I work on this, please?

Go Ahead.

**Comment by ayushi-ras** [comment]
hey @ashwin3005 I can help you in this . Please Assign

**Comment by ashwin3005** [comment]
> hey @ashwin3005 I can help you in this . Please Assign

Okay, Go ahead.
But don't change the UI completely.
Just add a toggle button for dark theme at the corner.

**Comment by ayushi-ras** [comment]
hey @ashwin3005 added the toggle , please check the PR and if possible label it as hactoberfest-accepted

**Comment by ashwin3005** [comment]
Can You please make the changes mentioned..

I will add label for sure..

**Comment by ayushi-ras** [comment]
@ashwin3005 What changes ?

**Comment by ashwin3005** [comment]
see in pull request..

**Comment by ayushi-ras** [comment]
@ashwin3005 sorry but not able to make whole website black as there is form
I have changed color to green to make headings to be clearly readable in dark mode.

**Comment by ashwin3005** [comment]
> @ashwin3005 sorry but not able to make whole website black as there is form I have changed color to green to make headings to be clearly readable in dark mode.

No problem, make some other contribution if you want

**Comment by SarahADev** [comment]
@ashwin3005 I'd like to try resolve this if you could please assign it to me.

**Comment by ashwin3005** [comment]
Go ahead..
