### ISSUE TITLE
Improve README.md 

### ISSUE THREAD

**Issue by ashwin3005** [ashwin3005/password-generator#5]
Try improving the README.md file if possible

**Comment by Dimas-Saputra-Me** [comment]
Can I work on this issue?

**Comment by ashwin3005** [comment]
> Can I work on this issue?

Go ahead.

**Comment by Dimas-Saputra-Me** [comment]
> Go ahead.

I've made a PR here #6 
Let me know if I need to change or add something more in the README, Thank you.
