### ISSUE TITLE
Input box for mobile view

### ISSUE THREAD

**Issue by ashwin3005** [ashwin3005/password-generator#53]
The input box for the mobile view is not good. It is not displaying the full value.

**Comment by ashwin3005** [comment]
Go ahead

**Comment by Ravina-Deogadkar** [comment]
![image](https://user-images.githubusercontent.com/49125074/195812332-15d1f795-142b-4fd0-aced-1c3674c257b0.png)
Does this looks good?

**Comment by Ravina-Deogadkar** [comment]
![image](https://user-images.githubusercontent.com/49125074/195984089-7dd68a16-431c-4894-ab86-98a345774192.png)
Reduced size and aligned to center

**Comment by ashwin3005** [comment]
oaky..
Now make a PR without conflict
