### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by wavpro** [ashwin3005/password-generator#67]
**Describe the bug**

**To Reproduce**
1. Go to ['...'](https://create-your-password.netlify.app/)
2. Click on the text for any of the checkboxes other than lower case.
3. See the issue.

**Expected behavior**
Each text should correspond to the correct checkbox.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: V1.14.122

**Additional context**
Please assign this issue to me, I'll be fixing it today.

**Comment by ashwin3005** [comment]
Can you attach the screen shot of the bug?

**Comment by wavpro** [comment]
> Can you attach the screen shot of the bug?

It's hard to show in a screenshot, so I recorded it https://streamable.com/vjp5bu
